// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotSpotifyAPI.Infrastructure.Persistence;

#nullable disable

namespace NotSpotifyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230523144048_songsModification")]
    partial class songsModification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.CurrentSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<string>("LinkRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CurrentSong");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<string>("LinkRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPlaylistsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPlaylistsId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.PlaylistSongs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlaylistSongs");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<string>("LinkRef")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlaylistSongsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistSongsId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.UserPlaylists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlaylists");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.Playlist", b =>
                {
                    b.HasOne("NotSpotifyAPI.Domain.Models.User", null)
                        .WithMany("Playlist")
                        .HasForeignKey("UserId");

                    b.HasOne("NotSpotifyAPI.Domain.Models.UserPlaylists", null)
                        .WithMany("Playlist")
                        .HasForeignKey("UserPlaylistsId");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.Song", b =>
                {
                    b.HasOne("NotSpotifyAPI.Domain.Models.PlaylistSongs", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistSongsId");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.UserPlaylists", b =>
                {
                    b.HasOne("NotSpotifyAPI.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.PlaylistSongs", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.User", b =>
                {
                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("NotSpotifyAPI.Domain.Models.UserPlaylists", b =>
                {
                    b.Navigation("Playlist");
                });
#pragma warning restore 612, 618
        }
    }
}
